# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

import yaml
from pathlib import Path

report: "report/workflow.rst"

configfile : "config/config.yaml"

MAX_VALUES = {
    "point-sources": 340.0,
    "disk1": 500,
    "disk2": 500,
    "disk3": 500,
    "spiral1": 200,
    "spiral2": 200,
    "spiral3": 200,
    "spiral4": 200,
    "spiral5": 1000,
}


with Path("config/template.yaml").open("r") as f:
    config_template = yaml.safe_load(f)

METHODS = [_["name"] for _ in config_template["runs"]]

include: "rules/init-config.smk"
include: "rules/run-comparison.smk"
include: "rules/plot-results.smk"


# all rule 
rule all:
    input:
        expand("results/{scenario}/{bkg_level}/{prefix}/{method}/images/flux.png", scenario=config["scenarios"], bkg_level=config["bkg_levels"], prefix=config["prefixes"], method=METHODS)
