# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

import yaml
from pathlib import Path

BKG_LEVELS = {
    "bg1": 0.01,
    "bg2": 0.1,
    "bg3": 1,
}

NAMES = [
    "point-sources",
    "disk1",
    "disk2",
    "disk3",
    "spiral1",
    "spiral2",
    "spiral3",
    "spiral4",
    "spiral5"
]

MAX_VALUES = {
    "point-sources": 340.0,
    "disk1": 500,
    "disk2": 500,
    "disk3": 500,
    "spiral1": 200,
    "spiral2": 200,
    "spiral3": 200,
    "spiral4": 200,
    "spiral5": 1000,
}


PREFIXES = {
    "chandra": "chandra_gauss_fwhm4710_128x128",
    "xmm": "xmm_gauss_fwhm14130_128x128",
    "joint": "chandra_gauss_fwhm4710_128x128,xmm_gauss_fwhm14130_128x128",
}

with Path("config/template.yaml").open("r") as f:
    config_template = yaml.safe_load(f)

METHODS = [_["name"].lower().replace(" ", "-") for _ in config_template["runs"]]

include: "rules/init-config.smk"
include: "rules/run-comparison.smk"


# all rule 
rule all:
    input:
        expand("results/{name}/{bkg_level}/{prefix}/{method}/{name}-{bkg_level}-{method}-{prefix}-result.fits.gz", name=NAMES, bkg_level=BKG_LEVELS, prefix=PREFIXES, method=METHODS)
