# Conda environment for reducing fermi data
name: jolideco-comparison

channels:
  - conda-forge
  - bioconda

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.9
  - snakemake>=6.4.1
  - astropy>5.2
