prefixes:
  - chandra
  - xmm
  - joint
bkg_levels:
  bg1: 0.01
  bg2: 0.1
  bg3: 1.
scenarios:
  - point1
  - aster1
  - aster2
  - aster3
  - disk1
  - disk2
  - disk3
  - spiral1
  - spiral2
  - spiral3
  - spiral4
  - spiral5